### ISSUE TITLE
vim-instant-markdown compatibility

### ISSUE THREAD

**Issue by alexdunn** [plasticboy/vim-markdown#167] opened 2015-01-21 22:58 UTC
I'd love to be able to use both vim-markdown and vim-instant-markdown.  vim-markdown is great for editing markdown in vim, and vim-instant-markdown is great for seeing immediate markdown rendering previews of your work.  

I think the only issue is that vim-markdown sets the filetype of all .md files to `mkd`, while vim-instant-markdown executes on filetype `markdown`.  If I set a file's type to `markdown`, it starts working with vim-instant-markdown, but I lose my vim-markdown features.  Is there a particular reason vim-markdown uses `mkd`?  

Thanks!

**Comment by cirosantilli** [comment] 2015-02-21 09:31
Possible duplicate of: https://github.com/plasticboy/vim-markdown/issues/159

**Closed** 2015-02-21 09:32 UTC
Labels: bug, plugin-conflict
