### ISSUE TITLE
Highlighting of nested links.

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [plasticboy/vim-markdown#48] opened 2013-10-14 13:41 UTC
the problem

````
![description [with a nested](link) doesn't highlight correctly](image.png)
````

the patch:

````
syn region mkdLink matchgroup=mkdDelimiter      start="\\\@<!\[" end="\]\ze\s*[[(]" contains=@Spell containedin=mkdLink nextgroup=mkdURL,mkdID skipwhite oneline
````

it just adds "containedin=mkdLink" to the original mkdLink region.

not sure if that's correct, i don't have any experience with vim syntax files, but it works for me so far.

**Comment by ain** [comment] 2015-05-04 13:20
:+1: for a fix. Reproduced.

**Comment by shirosaki** [comment] 2016-01-21 08:18
That seems to be fixed on master.

**Closed by shirosaki** 2016-01-21 08:18 UTC
Labels: bug, confirmed, has-patch
