### ISSUE TITLE
:TableFormat removes alignment hints

### ISSUE THREAD

**Issue by humblehacker** [plasticboy/vim-markdown#265] opened 2016-02-24 17:45 UTC
Some markdown formats allow table column alignment to be specified using colons 

    | col 1  | col 2  |
    |:------:|:------:|
    |centered|centered|

But :TableFormat removes these colons.

**Comment by shirosaki** [comment] 2016-02-25 00:14
duplicate of #220

**Closed** 2016-02-25 01:48 UTC
Labels: bug, duplicate
