### ISSUE TITLE
Bad syntax highlighting with < character

### ISSUE THREAD

**Issue by ptzz** [plasticboy/vim-markdown#228] opened 2015-09-25 08:39 UTC
When I type the < character in the following example, "baz" will turn yellow, as well as all following lines.

* foo  < bar baz

**Comment by cirosantilli** [comment] 2015-10-06 11:29
Possible duplicate of: https://github.com/plasticboy/vim-markdown/issues/138

**Closed by cirosantilli** 2015-10-06 11:29 UTC
